### PR TITLE
♻️Updated the `requirements.txt` to use the dependency versions

### PR DESCRIPTION
**Pull request by Minty-cyber**

### CODE REVIEW

**Comment by Minty-cyber** [comment]
@n1rjal could you check it out?

**Review by n1rjal — APPROVED** [review]

**Comment by n1rjal** [comment]
Hi, can you also implement uv in workflow and format the files with `black` cli @Minty-cyber

**Comment by Minty-cyber** [comment]
> Hi, can you also implement uv in workflow and format the files with `black` cli @Minty-cyber

Sure thing

**Comment by n1rjal** [comment]
can you merge the recent main in it and fix the workflow issue here.
Thanks

**Pull request closed without merging**
